Milestone 5 - dynamic page
Khanetmoi/CapstoneProject pull request #2
Opened 2022-05-18 22:09 UTC by Khanetmoi

Capstone : Desktop
   - Implement the section "Featured speakers" with dynamic HTML.
   - Deploy the project and check to make sure everything works as planned.

2022-05-19 00:24 UTC, zainsadaqat requested changes
# Required Changes 🔁
# Hello @Khanetmoi   😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [ ] Video presentation is missing. Kindly record a loom video that contains the following and add the link in the README file.
 - Record a video presenting the features of the project.
 - The maximum length of the video is 5 minutes.
 - The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
 - The video contains a demo of the project, showing the pages in different screen sizes.
 - The video contains a highlight about a piece of the code that you find interesting or are proud of making.

- [ ] Please use the requested Font: Fonts should be used: Cocogoose, Lato
 
- [ ] The pages should look almost identical to the original design, outside the content differences.
#### [Required Design]
<img width="1062" alt="Screen Shot 2022-05-19 at 5 11 07 AM" src="https://user-images.githubusercontent.com/83048208/169175342-da67bd02-9a9e-4d6d-adac-951d00ef4152.png">

#### [Your Design]

<img width="1440" alt="Screen Shot 2022-05-19 at 5 12 47 AM" src="https://user-images.githubusercontent.com/83048208/169175888-396e5dc4-0cb4-406f-98f1-934c977640d6.png">

- [ ] Kindly left-align the paragraph to make it look similar to the required design 👍🏻 
<img width="1157" alt="Screen Shot 2022-05-19 at 5 13 56 AM" src="https://user-images.githubusercontent.com/83048208/169176040-5308013f-e9f9-44f8-b018-fec4cad5e3cb.png">

- [ ] Kindly work on the design.
#### [Required Design]
<img width="981" alt="Screen Shot 2022-05-19 at 5 15 29 AM" src="https://user-images.githubusercontent.com/83048208/169176168-e258a594-e4e6-4102-9658-3fdc9c23527f.png">

#### [Your Design]
- Some icons are missing and others are not using the required color. Kindly fix it.
<img width="1069" alt="Screen Shot 2022-05-19 at 5 16 57 AM" src="https://user-images.githubusercontent.com/83048208/169176277-57260f91-cdf9-4f06-846a-d46385740bbe.png">

#### [Rquired Design]
<img width="910" alt="Screen Shot 2022-05-19 at 5 17 17 AM" src="https://user-images.githubusercontent.com/83048208/169176318-849afa7b-bc2e-4fb7-854b-0ef28ae4e872.png">

#### [Your Design]
- There should be only two columns in the desktop version and there should be a checkbox image pattern behind each speaker's image. kindly fix this 👍🏻 
<img width="1301" alt="Screen Shot 2022-05-19 at 5 17 56 AM" src="https://user-images.githubusercontent.com/83048208/169176374-dbd13c4e-32e9-4d63-9af3-890c7cd532b9.png">

_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-19 22:10 UTC, Munsa1 requested changes
# Required Changes
Hi @Khanetmoi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark:  Passing Linters
:heavy_check_mark:  Correct Gitflow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [x] Please add video link to your PR description

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 07:33 UTC, danmainah requested changes
Hi @Khanetmoi , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 07:33 UTC, danmainah commented on README.md
> +# Video Presentation
- [ ] [OPTIONAL] In the future I would recommend installing Krisp it gives your every week to record clear sound and removes the background noise, it works very well with zoom and loom.

2022-05-20 07:33 UTC, danmainah commented on about.html
> +                <li><a href="about.html">About Us</a> </li>
- [ ] [OPTIONAL] It would be nice to remove the about page link when you are already in the about page.

2022-05-20 07:33 UTC, danmainah commented on index.html
> +                <li><a href="about.html">About Us</a> </li>
- [ ] [OPTIONAL] It would be nice to remove the home page link when you are already on the home page.

2022-05-20 07:33 UTC, danmainah commented on index.html
> +    <section id="programs">
- [ ] As previously requested kindly ensure this section has only five programs as shown In the design given, kindly remove the extra projects and also make sure the design matches the given design

2022-05-20 08:27 UTC, prolajumokeoni approved these changes
Hi @Khanetmoi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-20 08:28 UTC, merged